-- ZOX: signals v1 (2025-10-01)
-- Estrutura canônica para ingestão de sinais via Edge Function

create table if not exists public.signals (
  id          bigint generated by default as identity primary key,
  source      text not null,
  ok          boolean not null default false,
  payload     jsonb,
  created_at  timestamptz not null default now()
);

-- RLS sempre ligado
alter table public.signals enable row level security;

-- leitura pública (apenas SELECT)
drop policy if exists signals_read_public on public.signals;
create policy signals_read_public
  on public.signals
  for select
  to anon, authenticated
  using (true);

-- índices úteis
create index if not exists idx_signals_created_at on public.signals (created_at desc);
create index if not exists idx_signals_source     on public.signals (source);
create index if not exists idx_signals_payload_gin on public.signals using gin (payload);

-- comentários
comment on table  public.signals is 'ZOX: Tabela de sinais recebidos via webhook_signals';
comment on column public.signals.payload is 'JSONB arbitrário com conteúdo do sinal';
